version: '3'

networks:
  local_network:
    external: true

services:
  socket-redis-cache:
    image: redis:alpine
    container_name: socket-redis-cache
    restart: unless-stopped
    ports:
      - 6378:6379
    networks:
      - local_network

  socket-service:
    image: socket-service
    container_name: socket-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - .env.production
    ports:
      - 5001:5001
    networks:
      - local_network
