name: Build and test source code (CI)
run-name: ${{ github.actor }} is building and testing the source code

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and test source code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Setup our npm registry
        run: echo "${{ secrets.NPMRC_FILE_CONTENT }}" > .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build source code
        run: npm run build --if-present

      # - name: Test source code
      #   run: npm run test --if-present
